#!/bin/bash

echo "================================================"
echo "   DK Holidays Admin Setup Instructions"
echo "================================================"
echo ""
echo "STEP 1: Get Firebase Admin SDK Key"
echo "-----------------------------------"
echo "1. Go to: https://console.firebase.google.com/"
echo "2. Select your project: 'dk-holidays'"
echo "3. Click Settings (⚙️) → Project Settings"
echo "4. Go to 'Service Accounts' tab"
echo "5. Click 'Generate New Private Key'"
echo "6. Save the JSON file as:"
echo "   /home/sama/Desktop/DK Holidays/DK-Holidays-MERN/server/config/serviceAccountKey.json"
echo ""
echo "STEP 2: Sign in to the Application"
echo "-----------------------------------"
echo "1. Go to: http://localhost:3000/login"
echo "2. Click 'Continue with Google'"
echo "3. Sign in with your Google account"
echo ""
echo "STEP 3: Get Your User ID (UID)"
echo "-----------------------------------"
echo "1. Go to Firebase Console → Authentication"
echo "2. Find your user in the list"
echo "3. Copy the UID (it looks like: abc123xyz...)"
echo ""
echo "STEP 4: Make Yourself Admin"
echo "-----------------------------------"
echo "Run this command (replace YOUR_UID with actual UID):"
echo "cd /home/sama/Desktop/DK\ Holidays/DK-Holidays-MERN/server"
echo "node makeAdmin.js YOUR_UID"
echo ""
echo "STEP 5: Sign Out and Sign In Again"
echo "-----------------------------------"
echo "1. Click logout button in navbar"
echo "2. Sign in again with Google"
echo "3. You will now see 'Admin Dashboard' button in navbar!"
echo ""
echo "STEP 6: Access Admin Dashboard"
echo "-----------------------------------"
echo "Click on 'Admin Dashboard' button or go to:"
echo "http://localhost:3000/admin"
echo ""
echo "================================================"
